= Hands-on Disaster Recovery of OpenShift containers and VMs with Trident protect

This lab guide provides a walkthrough on using NetApp Trident Protect to enable Distaster Recovery Plan for both your VMs and your containers between two environments.

You will go through the steps to install the NetApp Trident Container Storage Interface (CSI) driver on a ROSA cluster, as well as how to configure it to provision volumes on a FSx for NetApp ONTAP file system.
You will then proceed with the installation of Trident Protect, and its configuration to store data and metadata on an AWS S3 bucket.

Last, you will learn how to backup and restore a container based application, as well as failover a VM on a secondary ROSA cluster. This lab contains task that are handled by an OpenShift admin as well as activities typically perfomed by an OpenShift user. The different personas are noted throughout the lab guide.

NOTE: Both Trident and Trident Protect are already installed on the primary cluster. But you will go through the deployment process for both on the secondary cluster.

Here is your agenda for today...

. Introduction & Overview
. Install and configure Trident in OpenShift (in secondary cluster) (Admin persona)
. Install and configure Trident protect in OpenShift (in secondary cluster) (Admin persona)
. Backup, Restore, and Failover for VMs (User persona)
.. Provision VMs in OpenShift Virtualization
.. Configure storage replication for VM workloads
.. Perform a Failover for VM workloads
. Bonus 1: More Virtual Machine features (User persona)
.. Restore a Virtual Machine from a snapshot
.. Add a second Virtual Machine to the project and test the failover
. Bonus 2: Backup, Restore, and Failover for container workloads (User persona)
.. Provision container workloads
.. Backup/Restore container workloads
.. Configure storage replication for container workloads
.. Perform the Failover and Failback for container workloads

.. Provision container workloads
[[lab-setup]]
== Lab Setup

=== Authenticate `oc` to the cluster

The bastion provided with the RHDP workshop has the `aws` and `rosa` command line tools already installed and logged in.  The `oc` command is installed, but not authenticated.

To authenticate `oc` use the API URL, username, and password provided by the RHDP lab deployment.
