= Hands-on Disaster Recovery of OpenShift containers and VMs with Trident protect

This lab guide provides a walkthrough on using NetApp Trident Protect to enable a Disaster Recovery plan for both your VMs and your containers between two environments.

You will go through the steps to install the NetApp Trident Container Storage Interface (CSI) driver on a ROSA cluster, as well as how to configure it to provision volumes on an FSx for NetApp ONTAP file system. You will then proceed with the installation of Trident Protect and its configuration to store data and metadata on an AWS S3 bucket.

Finally, you will learn how to back up and restore a container-based application, as well as fail over a VM to a secondary ROSA cluster. This lab contains tasks that are handled by an OpenShift admin as well as activities typically performed by an OpenShift user. The different personas are noted throughout the lab guide.

NOTE: Both Trident and Trident Protect are already installed on the primary cluster. But you will go through the deployment process for both on the secondary cluster.

Here is your agenda for today:

Introduction & Overview::
  * Login details
  * Lab Description
 
Admin Persona: Configuration::
  * Install and configure Trident in OpenShift (Secondary Cluster)
  * Install and configure Trident Protect in OpenShift (Secondary Cluster)

User Persona: VM Operations::
  * Provision VMs in OpenShift Virtualization
  * Configure storage replication for VM workloads
  * Perform a Failover for VM workloads

Bonus 1: Advanced VM Features::
  * Restore a Virtual Machine from a snapshot
  * Add a second Virtual Machine to the project and test the failover

Bonus 2: Container Workloads::
  * Provision container workloads
  * Backup/Restore container workloads
  * Configure storage replication for container workloads
  * Perform the Failover and Failback for container workloads
  


