= Introducing Trident and Trident Protect
[[Introduction]]
## Introduction

While the persistent storage challenge has been effectively addressed by the CSI standard (Container Storage Interface), data protection introduces new complexities to overcome, especially when application consistency is required. With the growing demand to host VMs on container platforms, the protection of these workloads becomes essential.

This lab focuses on storage (NetApp Trident) and data protection (NetApp Trident Protect) capabilities provided by NetApp for both VM and container workloads.

Trident and Trident Protect provide data management for NetApp storage solutions on-premises and in the major hyperscalers: AWS, Azure, and Google Cloud. This includes first-party storage solutions based on NetApp technology: FSx for NetApp ONTAP, Azure NetApp Files, and Google Cloud NetApp Volumes, as well as self-managed storage available in all hyperscalers, such as Cloud Volumes ONTAP (CVO).

For this lab, the underlying storage service is AWS FSx for NetApp ONTAP, which provides fully managed shared storage with features like snapshots, cloning, and data tiering. The same capabilities are available in your own data center or any of the other major cloud providers, based on the consistent VM and application platform provided by OpenShift and the consistent storage and data management platform provided by NetApp ONTAP and Trident.

[[NetAppTrident]]
## NetApp Trident

NetApp Trident is a fully supported open-source project maintained by NetApp. It has been designed from the ground up to help you meet your containerized applications' persistence demands using industry-standard interfaces, such as the Container Storage Interface (CSI). Trident is available as a certified operator from the OpenShift OperatorHub. Trident features also address data protection, disaster recovery, portability, and migration use cases for Kubernetes workloads, leveraging NetApp’s industry-leading data management technology for snapshots, backups, replication, and cloning.

[[NetAppTridentProtect]]
## NetApp Trident Protect

NetApp Trident Protect provides advanced application data management capabilities that enhance the functionality and availability of stateful Kubernetes applications backed by the NetApp Trident CSI storage provisioner. Trident Protect simplifies the management, protection, and movement of containerized workloads across public clouds and on-premises environments. It also offers automation capabilities through its API and CLI.

The data protection capabilities provided by Trident Protect are only available if a storage solution based on the NetApp storage OS "ONTAP" is used. However, Trident Protect can also be used for data migration use cases from non-ONTAP storage to ONTAP storage. ONTAP is the most widely used storage system in the industry.

[[AWSFSxforNetAppONTAP]]
## AWS FSx for NetApp ONTAP

Amazon FSx for NetApp ONTAP is a native AWS storage service that allows customers to launch and run fully managed ONTAP file systems in the cloud. ONTAP is NetApp’s file system technology that provides a widely adopted set of data access and data management capabilities. Amazon FSx for NetApp ONTAP provides the familiar features, performance, and APIs of on-premises NetApp file systems with the agility, scalability, and simplicity of a fully managed AWS service.

---

